#!/usr/local/bin/python3
#here math is default module which comes inbuilt with python
#This is one way to import math module
"""
import math
print(math.pi)
print(math.pow(3,2))
"""
"""
#The another way of importing a module is
from math import *
#because of importing in this way we no need to use math.pi we can use pi directly
print(pi)
print(pow(3,2))
"""
"""
from math import pi,pow #we are importing only pi and pow
print(pi)
print(pow(3,2))
"""
import math as m
print(m,pi)
print(m,pow(3,2))







